### ISSUE TITLE
Can't run basic demo

### ISSUE THREAD

**Issue by tdewin** [justjavac/deno_win32#7]
```
 deno run --allow-ffi --unstable https://deno.land/x/win32/examples/MessageBox.ts
error: Uncaught TypeError: Invalid FFI pointer type, expected null, integer or BigInt
  return dll.symbols.MessageBoxW(
                     ^
    at Module.MessageBox (https://deno.land/x/win32@0.1.1/user32/MessageBox.ts:35:22)
    at https://deno.land/x/win32@0.1.1/examples/MessageBox.ts:3:24
```
```
deno --version
deno 1.30.3 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by justjavac** [comment]
U can use https://github.com/DjDeveloperr/deno_win32
